#!/usr/bin/env php
<?php
require 'vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

// ... register commands
$application->add(new App\Commands\SetupCommand());

$application->run();